# Generated by Django 4.2.1 on 2023-05-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='dishes/')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
