# Generated by Django 4.2.1 on 2023-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_remove_dish_ingredients_alter_dish_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/photos/'),
        ),
    ]
