# Generated by Django 4.2.1 on 2023-06-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_alter_dish_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
