# Generated by Django 4.2.1 on 2023-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_alter_dish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.CharField(choices=[('non-vegetarian', 'Non-Vegetarian'), ('vegetarian', 'Vegetarian')], default='non-vegan', max_length=20),
        ),
        migrations.AddField(
            model_name='dish',
            name='spiciness',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy')], default='mild', max_length=20),
        ),
    ]
