# Generated by Django 4.2.1 on 2023-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_dish_is_vegan_dish_spiciness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tag',
            field=models.CharField(choices=[('Pizze Rosse', 'Pizze Rosse'), ('Pizze Bianche', 'Pizze Bianche'), ('Makaron', 'Makaron'), ('Czarny Makaron', 'Czarny Makaron'), ('Przystawki', 'Przystawki'), ('Cafeteria', 'Cafeteria'), ('Bevande', 'Bevande'), ('Alcohol', 'Alcohol'), ('Gnocchi', 'Gnocchi'), ('Ravioli', 'Ravioli'), ('Lasagne', 'Lasagne'), ('Sałatki', 'Sałatki'), ('Zupy', 'Zupy')], max_length=50),
        ),
    ]
