# Generated by Django 4.2.1 on 2023-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0015_alter_dish_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='detail_description',
            field=models.TextField(blank=True),
        ),
    ]
